MealPlanner/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using MealPlanner.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MealPlanner.Controllers
{
    public class MenuController : Controller
    {
        private readonly MealPlannerDbContext _context;
        public MenuController(MealPlannerDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        [Authorize]
        public IActionResult AddMeals(List<Menu> itemList)
        {
            string userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (ModelState.IsValid)
            {
                foreach (Menu i in itemList)
                {
                    _context.Menu.Add(new Menu { UserId = userid, MealDate = i.MealDate, Item = i.Item, Meal = i.Meal, Calories =  i.Calories, Quantity = i.Quantity });
                }
                _context.SaveChanges();  
            }
            return RedirectToAction("ListMeals");
        }
        [Authorize]
        public IActionResult ListMeals()
        {
            string userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
            Menu user = _context.Menu.FirstOrDefault(x => x.UserId == userid);
            if (user != null)
            {
                var userMeals = _context.Menu.Where(x => x.UserId == userid).ToList();
                return View(userMeals);
            }
            else
            {
                return RedirectToAction("ErrorPage");
            }
        }
        [Authorize]
        public IActionResult UpdateQuantity(int itemId, int quantity)
        {
            Menu item = _context.Menu.Find(itemId);
            if(quantity == 0)
            {
                _context.Menu.Remove(item);
                _context.SaveChanges();
            }
            if(item != null && quantity > 0)
            {
                item.Quantity = quantity;
                _context.Entry(item).State = EntityState.Modified;
                _context.Update(item);
                _context.SaveChanges();
            }
            return RedirectToAction("ListMeals");
        }
    }
}

MealPlanner/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using MealPlanner.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MealPlanner.Controllers
{
    public class RecipeController : Controller
    {
        private readonly MealPlannerDbContext _context;
        private readonly RecipeDALInterface _recapi;
   
        public RecipeController(MealPlannerDbContext context, RecipeDALInterface recapi)
        {
            _context = context;
            _recapi = recapi;
         
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> RecipeList(string ingredient)
        {
            Recipe recipes = await _recapi.GetRecipes(ingredient);
            return View(recipes);

        }
        public async Task<IActionResult> Details(string id)
        {
            RecipeDetail recipe = await _recapi.RecipeDetails(id);
         
            return View(recipe);
        }
        [Authorize]
        public IActionResult AddFavorite(string id, string name)
        {
            string userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
            FavoriteRecipes fav = new FavoriteRecipes { UserId = userid, RecipeId = id, RecipeName = name};
            if(_context.FavoriteRecipes.Where(x =>(x.UserId == userid) && (x.RecipeId == id)).ToList().Count > 0)
            {
                return RedirectToAction("ListFavorites");
            }
            if(ModelState.IsValid)
            {
                _context.FavoriteRecipes.Add(fav);
                _context.SaveChanges();
            }
            return RedirectToAction("ListFavorites");
        }
        [Authorize]
       public IActionResult ListFavorites()
        {
            string userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
            List<FavoriteRecipes> favList = _context.FavoriteRecipes.Where(x => x.UserId == userid).ToList();
            return View(favList);
        }
        [Authorize]
        public IActionResult RemoveFavorite(int id)
        {
            string userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
            FavoriteRecipes fav = _context.FavoriteRecipes.FirstOrDefault(x => (x.UserId == userid) && (x.FavId == id));
            if(fav != null)
            {
                _context.FavoriteRecipes.Remove(fav);
                _context.SaveChanges();
            }
            return RedirectToAction("ListFavorites");
        }
    }
}

MealPlanner/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Meal Planner</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Meal Planner</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Recipe" asp-action="ListFavorites">Favorite Recipes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Menu" asp-action="ListMeals">Menu</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MealPlanner - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>